### ISSUE TITLE
Checking if the datetime is a Luxon DateTime fails

### ISSUE THREAD

**Issue by Jopie01** [cibernox/ember-power-calendar-luxon#35]
I upgraded all my packages in my app to their most recent versions and walk into the problem that the date is not displayed anymore but I get `Invalid Date`.

As it turns out https://github.com/cibernox/ember-power-calendar-luxon/blob/7605c26f4bd0f425cb37551c9fa2a6eac8c3cfe8/ember-power-calendar-luxon/src/index.js#L178 is the culprit. It seems that the `instanceof` check doesn't work anymore. I had to replace it with
```typescript
let datetime = DateTime.isDateTime(date) ? date : DateTime.fromJSDate(date);
```

I'm using Luxon 3.4.3

**Comment by mkszepp** [comment]
@Jopie01 thanks for reporting... i have fixed in `v0.7.2`
